# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std_phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
