# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('dist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dist_name', models.CharField(max_length=200, unique=True)),
                ('dist_div', models.CharField(max_length=200)),
            ],
        ),
    ]
